name: four_five_zero
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: 0.20.2
  auto_route: 9.3.0+1


  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  auto_route_generator: 9.3.1

  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/logo_messengers/


  fonts:
    - family: Montserrat-Bold_700
      fonts:
        - asset: assets/fonts/Montserrat-Bold_700.ttf
    - family: Montserrat-Medium_500
      fonts:
        - asset: assets/fonts/Montserrat-Medium_500.ttf

